/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package music.register;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.ResultSet;

/**
 *
 * @author oakridge
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordTF = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login Frame");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Password");

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(usernameTF)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jButton1)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String ID = usernameTF.getText();
        String str = null;
        Statement stmt=null;
        ResultSet rs = null;
        
        char[][] key_grid  = { {'t','u','a','f','z'},
                               {'s','k','r','m','o'},
                               {'b','g','e','q','v'},
                               {'w','y','d','c','i'},
                               {'h','x','l','p','n'}};
        
        String password = passwordTF.getText();
        String encrypted = "";
        
       int i=0;
        if (password.length() % 2 ==1)
        {
            password = password + "z";
        }
        
      for (int counter =1; counter<=4 ; i=i+2)
         {
       if ((pos_x(i, password, key_grid)!= pos_x((i+1), password, key_grid)
        && (pos_y(i, password, key_grid)!= pos_y((i+1), password, key_grid))))
        {
            int new_y_1 = pos_x((i+1), password, key_grid);
            int new_x_1 = pos_y(i, password, key_grid);
            
            int new_y_2 = pos_x(i, password, key_grid);
            int new_x_2 = pos_y((i+1), password, key_grid);
            
            
            encrypted = encrypted + (key_grid[new_x_1][new_y_1]) + (key_grid[new_x_2][new_y_2]);
           
        }
        
        else if ((pos_x(i, password, key_grid)== pos_x((i+1), password, key_grid)
        && (pos_y(i, password, key_grid)!= pos_y((i+1), password, key_grid))))
        {
            int new_y_1 = pos_x((i), password, key_grid) ;
            int new_x_1 = pos_y(i, password, key_grid) + 1;
                if (new_x_1 ==5)
                {
                    new_x_1 = 0;
                }
            
            int new_y_2 = pos_x((i+1), password, key_grid) ;
            int new_x_2 = pos_y((i+1), password, key_grid)+1;
                if (new_x_2 ==5)
                {
                    new_x_2 = 0;
                }
            
        
            encrypted = encrypted + (key_grid[new_x_1][new_y_1]) + (key_grid[new_x_2][new_y_2]);
          
           
        }
    
        else if ((pos_x(i, password, key_grid)!= pos_x((i+1), password, key_grid)
        && (pos_y(i, password, key_grid)== pos_y((i+1), password, key_grid))))
        {
            int new_y_1 = pos_x((i), password, key_grid) + 1;
                if (new_y_1 ==5)
                {
                    new_y_1 = 0;
                }
            int new_x_1 = pos_y(i, password, key_grid);
            
            
            int new_y_2 = pos_x((i+1), password, key_grid) + 1;
                if (new_y_2 ==5)
                {
                    new_y_2 = 0;
                }
            int new_x_2 = pos_y((i+1), password, key_grid);
            
        
            encrypted = encrypted + (key_grid[new_x_1][new_y_1]) + (key_grid[new_x_2][new_y_2]);
            
        }
        
        counter ++;
    }
   
            
        try {
            
            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost:3306/musicregister";
            Connection conn = (Connection) DriverManager.getConnection(database, "root", "oakridge");
            stmt = (Statement) conn.createStatement();
            String sql = "select * from login where username = '" + ID + "'";
            rs = stmt.executeQuery(sql);
            rs.next();
            str = rs.getString("password");
            
            if(str.equals(encrypted)) {
                MainFrame MainFrame =new MainFrame();
                MainFrame.setVisible(true);
                this.dispose();
                } else {
                
                jOptionPane1.showMessageDialog(rootPane,"Invalid Username/Password");
            }
            
            rs.close();
            stmt.close();
            conn.close();
      
        } catch (Exception e) {
            
            if (usernameTF.getText() == "" || passwordTF.getText() == "" ) {
                jOptionPane1.showMessageDialog(rootPane ,"Please enter a Username/Password");
                
            }else {
                jOptionPane1.showMessageDialog(rootPane ,"Invalid Username/Password");
            }     
           
            
            passwordTF.setText("");
            usernameTF.setText("");
            usernameTF.requestFocus();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }
    
       public static int pos_y(int pos, String password, char[][] key_grid)
        {
            int pos_y;
            for (int i=0; i<=4; i++)
            {
                for (int j=0; j<=4; j++)
                {
                    if (password.charAt(pos) == key_grid[i][j])
                    {
                        pos_y=i;
                        return pos_y;
                    }
                }
            }
            return 0;
        }
       
        public static int pos_x(int pos, String password, char[][] key_grid)
        {
            int pos_x;
            for (int i=0; i<=4; i++)
            {
                for (int j=0; j<=4; j++)
                {
                    if (password.charAt(pos) == key_grid[i][j])
                    {
                        pos_x=j;
                        return pos_x;
                    }
                }
            }
            return 0;
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
